GET http://localhost:8080/api/equipments/user
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTYwODIyMzkzNiwiZXhwIjoxNjA4MjIzOTU2fQ.02BwkN5XjSbHQYZvGKXIsfxeTRZKTgEs2RL_qo1qSKI


###
POST http://localhost:8080/login
Content-type: application/json

{
    "id":2,
    "password":123456
}
###
POST http://localhost:8080/api/calendar
Content-type: application/json

{
"endTime": "Thu Dec 24 2020 03:00:00 GMT+0200 (שעון ישראל (חורף))",
"startTime": "Thu Dec 24 2020 0:30:00 GMT+0200 (שעון ישראל (חורף))",
"subject": "קרב מגע וקאדרים ",
"userId":2
}

###

patch http://localhost:8080/api/notes/3
Content-Type: application/json

{
    "title":"exercesice"
}

###

DELETE http://localhost:8080/api/calendar/23
content-type: application/json

{
}
